# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/joystick_ports.xdc

# IP: ip/xadc_wiz_0/xadc_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet

# XDC: c:/Users/jstoddar/Documents/ZyboZ7-Analog-Joystick/ZyboZ7-Analog_Joystick.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc

# XDC: c:/Users/jstoddar/Documents/ZyboZ7-Analog-Joystick/ZyboZ7-Analog_Joystick.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
